version: '3.8'
services:
  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
